@startuml

title __CARDCHAIN's Class Diagram__\n

  namespace com.example.cardchain {
    class com.example.cardchain.Adapter {
        - context : Context
        - layoutInflater : LayoutInflater
        - models : List<Model>
        + Adapter()
        + destroyItem()
        + getCount()
        + instantiateItem()
        + isViewFromObject()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.AuthenticationHandler {
        ~ mAuth : FirebaseAuth
        - email : String
        - password : String
        - user : FirebaseUser
        + forgotPassword()
        + signIn()
        + signUp()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.ForgotPasswordActivity {
        ~ emailField : EditText
        ~ forgProg : ProgressBar
        ~ forg_btn : Button
        - TAG : String
        - email : String
        + onBackPressed()
        + returnToLoginFunc()
        + successDialog()
        # onCreate()
        # onResume()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.HomeActivity {
        {static} + HomeAct : Activity
        ~ auth : FirebaseAuth
        ~ logoutBtn : ImageButton
        ~ meowNav : MeowBottomNavigation
        {static} - ADD_CARD_ID : int
        {static} - LIST_CARD_ID : int
        {static} - SLIDE_ID : int
        - alreadyCalled : boolean
        - toolBar : Toolbar
        + onActivityResult()
        + onAuthStateChanged()
        # onCreate()
        # onStart()
        # onStop()
        - startLoginActivity()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.LoginActivity {
        {static} - HOME_LOGIN_SIGNAL : int
        {static} - TAG : String
        - emailField : EditText
        - emailId : String
        - login : Button
        - loginProg : ProgressBar
        - passField : EditText
        - password : String
        - sharedPref : SharedPreferences
        + forgotPassFunc()
        + onBackPressed()
        + returnToWelcomeFunc()
        # onCreate()
        # onResume()
        - updateUI()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.Model {
        - image : int
        + Model()
        + getImage()
        + setImage()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.ProfileActivity {
        # onCreate()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.SignUpActivity {
        {static} # TAG : String
        ~ confpassField : EditText
        ~ emailField : EditText
        ~ passField : EditText
        ~ signUpButton : Button
        - confPass : String
        - emailId : String
        - pass : String
        - progressBar : ProgressBar
        + onBackPressed()
        + returnToWelcomeFunc()
        + successDialog()
        # onCreate()
        # onResume()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.SplashScreen {
        {static} - SPLASH_TIME_OUT : int
        {static} - currentActivity : String
        - mAuth : FirebaseAuth
        # onCreate()
        # onStart()
        # updateUI()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.Validation {
        + emailValidation()
        + passwordStrength()
    }
  }
  

  namespace com.example.cardchain {
    class com.example.cardchain.WelcomeActivity {
        + LoginFunc()
        + SignUpFunc()
        # onCreate()
    }
  }
  

  com.example.cardchain.Adapter -up-|> androidx.viewpager.widget.PagerAdapter
  com.example.cardchain.ForgotPasswordActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.cardchain.HomeActivity .up.|> com.google.firebase.auth.FirebaseAuth.AuthStateListener
  com.example.cardchain.HomeActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.cardchain.LoginActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.cardchain.ProfileActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.cardchain.SignUpActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.cardchain.SplashScreen -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.cardchain.WelcomeActivity -up-|> androidx.appcompat.app.AppCompatActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
